-- Game dimensions
GAME_WIDTH = 1280
GAME_HEIGHT = 720

-- Font stuff
FONT_PATH = "media/fonts/PTM55FT.ttf"
DEFAULT_FONT_SIZE = 20
LOG_FONT_SIZE = 15
MENU_FONT_SIZE = 23
QUOTE_FONT_SIZE = 35
SHIELDS_FONT_SIZE = 28
TITLE_FONT_SIZE = 55

-- Drone stuff
STARTING_ATTACK_DRONES = 2.734159e6
STARTING_EXPLORATION_DRONES = 2.1231e7
STARTING_MINING_DRONES = 3.14159e7
DRONE_COUNT_QUEUE_LENGTH = 500
DRONE_CLUSTER_SIZE = 1e6
ATTACK_TYPE = "attack"
EXPLORE_TYPE = "explore"
MINE_TYPE = "mine"
MAX_DRONE_MESSAGES = 7

-- Characters
PROPANE_MIKE = "propanemike01"
